# Generated by Django 3.1.4 on 2021-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210204_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_votes',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
