# Generated by Django 3.1.4 on 2021-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_max_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_votes',
            field=models.IntegerField(verbose_name='Maximum votes'),
        ),
    ]
