# Generated by Django 3.1.4 on 2021-02-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
