# Generated by Django 3.1.4 on 2021-02-26 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='authored_posts', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorited_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
